name: CloudSystem
author: konrad2002
version: 0.1
main: net.grexcraft.cloud_plugin.CloudSystemPlugin
load: POSTWORLD
commands:
  modifyserver:
    description: Change server state in cloud service
    usage: /modifyserver <state>
    permission: grexcraft.cloud.modifyserver
  whereami:
    description: get name of current server
    usage: /whereami